# Generated by Django 3.2.10 on 2021-12-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
