# Generated by Django 3.2.10 on 2021-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0004_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pac',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
