# Generated by Django 3.2.10 on 2021-12-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0008_alter_useraccount_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
