# Generated by Django 3.2.10 on 2022-01-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0010_useraccountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountdetails',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='useraccountdetails',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='useraccountdetails',
            name='password',
        ),
    ]
