# Generated by Django 3.2.10 on 2022-01-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0011_auto_20220103_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
