# Generated by Django 3.2.10 on 2022-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_authentication', '0012_delete_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetails',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
