# Generated by Django 3.2.10 on 2022-01-05 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(max_length=8)),
                ('Address', models.TextField()),
                ('LGA', models.CharField(max_length=50)),
                ('Name_of_Next_of_Kln', models.CharField(max_length=50)),
                ('Next_of_Kln_email_address', models.EmailField(max_length=254)),
                ('Next_of_Kln_phone', models.CharField(max_length=13)),
                ('Next_of_Kln_address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
