# Generated by Django 3.2.10 on 2022-01-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_dashboard', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
