# Generated by Django 3.2.10 on 2022-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_dashboard', '0011_alter_userservicestatus_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookverification',
            name='Date',
            field=models.DateTimeField(max_length=8),
        ),
    ]
