# Generated by Django 3.2.10 on 2022-01-21 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pension_user_dashboard', '0012_alter_bookverification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
