# Generated by Django 3.2.10 on 2022-02-01 05:49

from django.db import migrations, models
import pension_user_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_dashboard', '0014_userwalletdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(blank=True, upload_to=pension_user_dashboard.models.UserProfile.nameFile),
        ),
    ]
