# Generated by Django 3.2.10 on 2022-02-01 07:20

from django.db import migrations, models
import pension_user_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_user_dashboard', '0015_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(blank=True, default='None', upload_to=pension_user_dashboard.models.UserProfile.nameFile),
        ),
    ]
